"""Добавление полей в таблицу

Revision ID: 7be6094c35bd
Revises: 
Create Date: 2025-04-06 13:01:13.741342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be6094c35bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_logs', sa.Column('balance', sa.Float(), nullable=False))
    op.add_column('wallet_logs', sa.Column('energy', sa.Float(), nullable=False))
    op.add_column('wallet_logs', sa.Column('bandwidth', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_logs', 'bandwidth')
    op.drop_column('wallet_logs', 'energy')
    op.drop_column('wallet_logs', 'balance')
    # ### end Alembic commands ###
