"""Добавление полей в таблицу2

Revision ID: b724ddcb48e9
Revises: 
Create Date: 2025-04-06 13:04:56.334106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b724ddcb48e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_logs', sa.Column('balance', sa.Float(), server_default='0', nullable=False))
    op.add_column('wallet_logs', sa.Column('energy', sa.Float(), server_default='0', nullable=False))
    op.add_column('wallet_logs', sa.Column('bandwidth', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_logs', 'bandwidth')
    op.drop_column('wallet_logs', 'energy')
    op.drop_column('wallet_logs', 'balance')
    # ### end Alembic commands ###
